import type {
  Usuario, Equipe, Membro, Evento, Palestrante,
  SolicitacaoPatrocinio, RequisicaoImpressao, ConfiguracaoIntegracao, Notificacao
} from '../types';

export const USUARIOS_PADRAO: Usuario[] = [
  { id: 'u-1', nome: 'Administrador AIprint', email: 'admin@aiprint.com', papel: 'admin', ativo: true },
  { id: 'u-2', nome: 'João Gestor', email: 'coordenador@aiprint.com', papel: 'coordenador', equipeId: 'eq-1', ativo: true },
  { id: 'u-3', nome: 'Carlos Mendes', email: 'membro@aiprint.com', papel: 'membro', telefone: '(12) 99901-0099', equipeId: 'eq-1', ativo: true },
  { id: 'u-4', nome: 'Rodrigo Produção', email: 'producao@aiprint.com', papel: 'producao', ativo: true },
  { id: 'u-5', nome: 'Ana Gestora', email: 'gestor2@aiprint.com', papel: 'coordenador', equipeId: 'eq-2', ativo: true },
  { id: 'u-6', nome: 'Marcos Gestor', email: 'gestor3@aiprint.com', papel: 'coordenador', equipeId: 'eq-3', ativo: true },
  { id: 'u-7', nome: 'Natasha Negreiros', email: 'trio@aiprint.com', papel: 'trio', telefone: '(12) 99901-0001', equipeId: 'eq-1', ativo: true },
];

export const EQUIPES_PADRAO: Equipe[] = [
  {
    id: 'eq-1',
    nome: 'VP INSPIRE',
    regional: 'Regional Leste Paulista',
    cidade: 'São José dos Campos/SP',
    gestoresIds: ['u-2'],
    stats: {
      totalMembros: 25,
      referenciasInternas: 677,
      referenciasExternas: 897,
      reunioes1a1: 1556,
      convidados: 288,
      educacao: 2552,
      negociosGeradosReais: 3261522.00,
    },
    statsUltimoMes: {
      membrosAtivos: 23,
      referenciasInternas: 69,
      referenciasExternas: 53,
      reunioes1a1: 98,
      convidados: 26,
      negociosGeradosReais: 72869.00,
    },
    especialidadesAberto: [
      'Material de construção',
      'Plano de saúde',
      'Cafeteria',
      'Energia Fotovoltaica',
      'Materiais para piscina',
      'Administradora de Condomínios',
      'Petshop',
      'Consultora de Produtos de Beleza',
    ],
    patrocinadores: [
      { id: 'pat-1', nome: 'Negreiros Sociedade de Advogados', equipeId: 'eq-1' },
      { id: 'pat-2', nome: 'Samatos Financeira', equipeId: 'eq-1' },
      { id: 'pat-3', nome: 'IBH PNL', equipeId: 'eq-1' },
      { id: 'pat-4', nome: 'Adonai RH', equipeId: 'eq-1' },
    ],
  },
  {
    id: 'eq-2',
    nome: 'BNI Conexão Centro',
    regional: 'Regional Metropolitana',
    cidade: 'São Paulo/SP',
    gestoresIds: ['u-5'],
    stats: {
      totalMembros: 18,
      referenciasInternas: 312,
      referenciasExternas: 420,
      reunioes1a1: 890,
      convidados: 145,
      educacao: 1200,
      negociosGeradosReais: 1540000.00,
    },
    statsUltimoMes: {
      membrosAtivos: 17,
      referenciasInternas: 38,
      referenciasExternas: 45,
      reunioes1a1: 72,
      convidados: 15,
      negociosGeradosReais: 48500.00,
    },
    especialidadesAberto: [
      'Consultoria Financeira',
      'Fisioterapia',
      'Decoração de Interiores',
      'Energia Solar',
    ],
    patrocinadores: [
      { id: 'pat-5', nome: 'Conexão Seguros', equipeId: 'eq-2' },
      { id: 'pat-6', nome: 'Centro Contábil', equipeId: 'eq-2' },
    ],
  },
  {
    id: 'eq-3',
    nome: 'BNI Progresso Sul',
    regional: 'Regional Campinas',
    cidade: 'Campinas/SP',
    gestoresIds: ['u-6'],
    stats: {
      totalMembros: 21,
      referenciasInternas: 445,
      referenciasExternas: 520,
      reunioes1a1: 1100,
      convidados: 198,
      educacao: 1800,
      negociosGeradosReais: 2100000.00,
    },
    statsUltimoMes: {
      membrosAtivos: 20,
      referenciasInternas: 52,
      referenciasExternas: 61,
      reunioes1a1: 88,
      convidados: 22,
      negociosGeradosReais: 65200.00,
    },
    especialidadesAberto: [
      'Advocacia Trabalhista',
      'Clínica Odontológica',
      'Escola de Idiomas',
    ],
    patrocinadores: [
      { id: 'pat-7', nome: 'Progresso Imóveis', equipeId: 'eq-3' },
      { id: 'pat-8', nome: 'Sul Tecnologia', equipeId: 'eq-3' },
      { id: 'pat-9', nome: 'Campinas Advocacia', equipeId: 'eq-3' },
    ],
  },
];

export const MEMBROS_PADRAO: Membro[] = [
  { id: 'm-1', nome: 'Natasha Negreiros', empresa: 'Negreiros Advocacia', especialidade: 'Advocacia Empresarial', contato: '(12) 99901-0001', nivel: 'Presidente / Trio', equipeId: 'eq-1' },
  { id: 'm-2', nome: 'Diogo Palmeira', empresa: 'Palmeira Advocacia', especialidade: 'Direito Civil', contato: '(12) 99901-0002', nivel: 'Vice-Presidente / Trio', equipeId: 'eq-1' },
  { id: 'm-3', nome: 'Priscila de Ávila', empresa: 'Prudenza Marcas e Patentes', especialidade: 'Propriedade Intelectual', contato: '(12) 99901-0003', nivel: 'Secretário-Tesoureiro / Trio', equipeId: 'eq-1' },
  { id: 'm-4', nome: 'Helton Fonseca', empresa: 'Unify Segurança do Trabalho', especialidade: 'Segurança do Trabalho', contato: '(12) 99901-0004', nivel: 'Coordenador de Educação', equipeId: 'eq-1' },
  { id: 'm-5', nome: 'Philipe Gerber', empresa: 'Agência Gerber', especialidade: 'Marketing Digital', contato: '(12) 99901-0005', nivel: 'Coordenador de Mídias', equipeId: 'eq-1' },
  { id: 'm-6', nome: 'Rennan Marcondes', empresa: 'MAC Projetos e Construções', especialidade: 'Construção Civil', contato: '(12) 99901-0006', nivel: 'Coordenador de Comunicação', equipeId: 'eq-1' },
  { id: 'm-7', nome: 'Marcelo Barcelos', empresa: 'IBHPNL', especialidade: 'Coaching / PNL', contato: '(12) 99901-0007', nivel: 'Coordenador de Mentoria', equipeId: 'eq-1' },
  { id: 'm-8', nome: 'Mariana Panerari', empresa: 'Panerari Assessoria', especialidade: 'Assessoria Contábil', contato: '(12) 99901-0008', nivel: 'Coordenadora de Reconhecimento', equipeId: 'eq-1' },
  { id: 'm-9', nome: 'Marcus Alvarenga', empresa: 'Alvarenga Consultoria', especialidade: 'Consultoria Empresarial', contato: '(12) 99901-0009', nivel: 'Membro', equipeId: 'eq-1' },
  { id: 'm-10', nome: 'Vanessa Lopes', empresa: 'Lopes Nutrição', especialidade: 'Nutrição e Saúde', contato: '(12) 99901-0010', nivel: 'Membro', equipeId: 'eq-1' },
  { id: 'm-11', nome: 'Ana Carolina Duarte', empresa: 'Duarte Engenharia', especialidade: 'Engenharia Elétrica', contato: '(12) 99901-0011', nivel: 'Membro', equipeId: 'eq-1' },
  { id: 'm-12', nome: 'Roberto Campos', empresa: 'RC Seguros', especialidade: 'Seguros de Vida e Automóvel', contato: '(12) 99901-0012', nivel: 'Membro', equipeId: 'eq-1' },
  { id: 'm-13', nome: 'Fernanda Souza', empresa: 'Souza Imóveis', especialidade: 'Corretagem Imobiliária', contato: '(12) 99901-0013', nivel: 'Membro', equipeId: 'eq-1' },
  { id: 'm-14', nome: 'Paulo Lima', empresa: 'Lima Tecnologia', especialidade: 'TI e Suporte', contato: '(12) 99901-0014', nivel: 'Membro', equipeId: 'eq-1' },
  { id: 'm-15', nome: 'Sandra Martins', empresa: 'SM Fotografia', especialidade: 'Fotografia Profissional', contato: '(12) 99901-0015', nivel: 'Membro', equipeId: 'eq-1' },
  { id: 'm-16', nome: 'Eduardo Vieira', empresa: 'Vieira Paisagismo', especialidade: 'Paisagismo e Jardinagem', contato: '(12) 99901-0016', nivel: 'Membro', equipeId: 'eq-1' },
  { id: 'm-17', nome: 'Juliana Castro', empresa: 'Castro Nutrição', especialidade: 'Nutrição Esportiva', contato: '(12) 99901-0017', nivel: 'Membro', equipeId: 'eq-1' },
  { id: 'm-18', nome: 'Rafael Andrade', empresa: 'Andrade Elétrica', especialidade: 'Instalações Elétricas', contato: '(12) 99901-0018', nivel: 'Membro', equipeId: 'eq-1' },
  { id: 'm-19', nome: 'Camila Rodrigues', empresa: 'CR Design', especialidade: 'Design Gráfico', contato: '(12) 99901-0019', nivel: 'Membro', equipeId: 'eq-1' },
  { id: 'm-20', nome: 'Lucas Ferreira', empresa: 'Ferreira Contabilidade', especialidade: 'Contabilidade Fiscal', contato: '(12) 99901-0020', nivel: 'Membro', equipeId: 'eq-1' },
  { id: 'm-21', nome: 'Tatiana Alves', empresa: 'Alves Fisioterapia', especialidade: 'Fisioterapia', contato: '(12) 99901-0021', nivel: 'Membro', equipeId: 'eq-1' },
  { id: 'm-22', nome: 'Fernando Santos', empresa: 'Santos Auto Center', especialidade: 'Mecânica Automotiva', contato: '(12) 99901-0022', nivel: 'Membro', equipeId: 'eq-1' },
  { id: 'm-23', nome: 'Beatriz Oliveira', empresa: 'Oliveira Estética', especialidade: 'Estética e Beleza', contato: '(12) 99901-0023', nivel: 'Membro', equipeId: 'eq-1' },
  { id: 'm-24', nome: 'Leonardo Costa', empresa: 'Costa Arquitetura', especialidade: 'Arquitetura Residencial', contato: '(12) 99901-0024', nivel: 'Membro', equipeId: 'eq-1' },
  { id: 'm-25', nome: 'Aline Nascimento', empresa: 'Nascimento Odontologia', especialidade: 'Odontologia', contato: '(12) 99901-0025', nivel: 'Membro', equipeId: 'eq-1' },
];

export const EVENTOS_PADRAO: Evento[] = [
  { id: 'ev-1', titulo: 'Reunião de Convidados', data: '2026-06-02', hora: '06:30', local: 'Estação Coronel Oriente', tipo: 'reuniao', equipeId: 'eq-1' },
  { id: 'ev-2', titulo: 'Festa Junina INSPIRE', data: '2026-06-20', hora: '18:00', local: 'A definir', tipo: 'social', equipeId: 'eq-1' },
  { id: 'ev-3', titulo: 'Festa de 1 Ano da Equipe INSPIRE', data: '2026-07-15', hora: '19:00', local: 'A definir', tipo: 'aniversario', equipeId: 'eq-1' },
  { id: 'ev-4', titulo: 'Reunião Semanal Regular', data: '2026-06-09', hora: '06:30', local: 'Estação Coronel Oriente', tipo: 'reuniao', equipeId: 'eq-1' },
  { id: 'ev-5', titulo: 'Reunião Semanal Regular', data: '2026-06-16', hora: '06:30', local: 'Estação Coronel Oriente', tipo: 'reuniao', equipeId: 'eq-1' },
  { id: 'ev-6', titulo: 'Reunião Semanal Regular', data: '2026-06-23', hora: '06:30', local: 'Estação Coronel Oriente', tipo: 'reuniao', equipeId: 'eq-1' },
  { id: 'ev-7', titulo: 'Reunião Semanal Regular', data: '2026-06-30', hora: '06:30', local: 'Estação Coronel Oriente', tipo: 'reuniao', equipeId: 'eq-1' },
  { id: 'ev-8', titulo: 'Reunião Mensal BNI Conexão Centro', data: '2026-06-10', hora: '07:00', local: 'Sala de Reuniões Central', tipo: 'reuniao', equipeId: 'eq-2' },
  { id: 'ev-9', titulo: 'Workshop de Networking BNI Progresso Sul', data: '2026-06-17', hora: '09:00', local: 'Hotel Campinas Business', tipo: 'outro', equipeId: 'eq-3' },
];

export const PALESTRANTES_PADRAO: Palestrante[] = [
  { id: 'pal-1', nome: 'Vanessa Lopes', data: '2026-06-09', equipeId: 'eq-1' },
  { id: 'pal-2', nome: 'Mariana Panerari', data: '2026-06-16', equipeId: 'eq-1' },
  { id: 'pal-3', nome: 'Marcelo Barcelos', data: '2026-06-23', equipeId: 'eq-1' },
  { id: 'pal-4', nome: 'Marcus Alvarenga', data: '2026-06-30', equipeId: 'eq-1' },
];

export const SOLICITACOES_PADRAO: SolicitacaoPatrocinio[] = [
  {
    id: 'sp-1',
    empresa: 'Negreiros Advocacia',
    equipeId: 'eq-1',
    equipeNome: 'VP INSPIRE',
    semana: '2026-06-02',
    valor: 850.00,
    status: 'aprovada',
    patrocinadorEmail: 'membro@aiprint.com',
    patrocinadorNome: 'Carlos Mendes',
    dataSolicitacao: '2026-05-28',
  },
  {
    id: 'sp-2',
    empresa: 'Samatos Financeira',
    equipeId: 'eq-1',
    equipeNome: 'VP INSPIRE',
    semana: '2026-06-09',
    valor: 850.00,
    status: 'aguardando_aprovacao',
    patrocinadorEmail: 'membro@aiprint.com',
    patrocinadorNome: 'Carlos Mendes',
    dataSolicitacao: '2026-06-01',
  },
  {
    id: 'sp-3',
    empresa: 'IBH PNL',
    equipeId: 'eq-2',
    equipeNome: 'BNI Conexão Centro',
    semana: '2026-06-10',
    valor: 750.00,
    status: 'concluida',
    patrocinadorEmail: 'membro@aiprint.com',
    patrocinadorNome: 'Carlos Mendes',
    dataSolicitacao: '2026-05-20',
  },
];

export const REQUISICOES_PADRAO: RequisicaoImpressao[] = [
  {
    id: 'req-1',
    equipeId: 'eq-1',
    equipeNome: 'VP INSPIRE',
    solicitanteEmail: 'coordenador@aiprint.com',
    solicitanteNome: 'João Gestor',
    quantidade: 350,
    dataEvento: '2026-06-09',
    observacoes: 'Mapa de referência para reunião semanal de junho.',
    status: 'em_producao',
    dataCriacao: '2026-06-01 09:00',
  },
  {
    id: 'req-2',
    equipeId: 'eq-2',
    equipeNome: 'BNI Conexão Centro',
    solicitanteEmail: 'gestor2@aiprint.com',
    solicitanteNome: 'Ana Gestora',
    quantidade: 200,
    dataEvento: '2026-06-10',
    observacoes: 'Mapa mensal de maio para reunião de junho.',
    status: 'pronto',
    dataCriacao: '2026-05-30 14:00',
  },
  {
    id: 'req-3',
    equipeId: 'eq-3',
    equipeNome: 'BNI Progresso Sul',
    solicitanteEmail: 'gestor3@aiprint.com',
    solicitanteNome: 'Marcos Gestor',
    quantidade: 280,
    dataEvento: '2026-06-17',
    observacoes: 'Mapa para workshop de networking.',
    status: 'recebido',
    dataCriacao: '2026-06-03 11:30',
  },
  {
    id: 'req-4',
    equipeId: 'eq-1',
    equipeNome: 'VP INSPIRE',
    solicitanteEmail: 'coordenador@aiprint.com',
    solicitanteNome: 'João Gestor',
    quantidade: 350,
    dataEvento: '2026-05-12',
    observacoes: 'Mapa de maio — entregue com sucesso.',
    status: 'entregue',
    dataCriacao: '2026-05-05 10:00',
  },
];

export const NOTIFICACOES_PADRAO: Notificacao[] = [
  {
    id: 'not-1',
    tipo: 'membro',
    mensagem: 'Carlos Mendes solicitou associação ao grupo VP INSPIRE.',
    timestamp: '02/06/2026 às 08:15',
    lida: false,
  },
  {
    id: 'not-2',
    tipo: 'patrocinador',
    mensagem: 'Samatos Financeira enviou solicitação de patrocínio para a semana de 09/06.',
    timestamp: '01/06/2026 às 14:30',
    lida: false,
  },
  {
    id: 'not-3',
    tipo: 'entrega',
    mensagem: 'Mapa de referência VP INSPIRE (350 cópias) marcado como Pronto para entrega.',
    timestamp: '01/06/2026 às 11:00',
    lida: true,
  },
  {
    id: 'not-4',
    tipo: 'sistema',
    mensagem: 'Nova requisição de impressão recebida da equipe VP INSPIRE para evento de 09/06.',
    timestamp: '01/06/2026 às 09:00',
    lida: true,
  },
];

export const INTEGRACOES_PADRAO: ConfiguracaoIntegracao[] = [
  {
    id: 'int-1',
    nome: 'PrintMaster Premium API',
    descricao: 'API de impressão gráfica de alta qualidade',
    url: 'https://api.printmaster.com/v3/print',
    chaveApi: 'pm_live_8fa389bcde20a',
    ativa: true,
  },
  {
    id: 'int-2',
    nome: 'WhatsApp Business API',
    descricao: 'Notificações automáticas via WhatsApp',
    url: 'https://api.whatsapp.business/v2/messages',
    chaveApi: 'wa_tok_382bc81fa3d',
    ativa: false,
  },
  {
    id: 'int-3',
    nome: 'Asaas Pagamentos',
    descricao: 'Integração de cobrança e pagamentos',
    url: 'https://api.asaas.com/v3/payments',
    chaveApi: 'aas_live_key_secret',
    ativa: false,
  },
];
